#MYSQL INSTALATION AND CONFIGURATION

```bash
sudo apt install mysql-server
sudo service mysql status
sudo ss -tap | grep mysql
sudo service mysql restart
sudo journalctl -u mysql
sudo systemctl restart mysql.service
```

## MYSQL CONSOLE COMMANDS
```bash
\help
\h or \?
Print help about MySQL Shell, or search the online help.
\quit
\q or \exit
Exit MySQL Shell.
\
In SQL mode, begin multiple-line mode. Code is cached and executed when an empty line is entered.
\status
\s
Show the current MySQL Shell status.
\js
Switch execution mode to JavaScript.
\py
Switch execution mode to Python.
\sql
Switch execution mode to SQL.
\connect
\c
Connect to a MySQL instance.
\reconnect
Reconnect to the same MySQL instance.
\disconnect
Disconnect the global session.
\use
\u
Specify the schema to use.
\source
\. or source (no backslash)
Execute a script file using the active language.
\warnings
\W
Show any warnings generated by a statement.
\nowarnings
\w
Do not show any warnings generated by a statement.
\history
View and edit command line history.
\rehash
Manually update the autocomplete name cache.
\option
Query and change MySQL Shell configuration options.
\show
Run the specified report using the provided options and arguments.
\watch
Run the specified report using the provided options and arguments, and refresh the results at regular intervals.
\edit
\e
Open a command in the default system editor then present it in MySQL Shell.
\pager
\P
Configure the pager which MySQL Shell uses to display text.
\nopager
Disable any pager which MySQL Shell was configured to use.
\system
\!
Run the specified operating system command and display the results in MySQL Shell.
\query_attribute
Enables you to define query attributes for your SQL queries. The MySQL Shell functionality is identical to that of the MySQL client.
```
